FROM ubuntu

#RUN touch /root/test1.txt
#RUN touch /root/test2.txt
#RUN touch /root/test3.txt
#RUN mkdir -p /root/child1
#RUN mkdir -p /root/child2

WORKDIR /root/

RUN touch ./test1.txt
RUN touch ./test2.txt
RUN touch ./test3.txt


RUN mkdir /root/testfolder

WORKDIR /root/testfolder

RUN mkdir ./child1
RUN mkdir ./child2
